"use client";

import { useEffect, useMemo, useState } from "react";

type Status = "Available" | "Nearly Full" | "Full" | "Closed" | "Cancelled" | "Completed";
type Session = { id:string|number; date:string; day:number; title:string; start:string; end:string; location:string; capacity:number; booked:number; status:Status; description:string };
type Registration = { id:string|number; sessionId:string|number; name:string; studentNumber:string; status:"Confirmed"|"Waitlisted" };

const seed: Session[] = [
  {id:1,date:"2026-07-03",day:3,title:"Robotics Workshop Volunteer Induction",start:"09:00",end:"10:30",location:"UWA EZONE · Learning Studio",capacity:18,booked:7,status:"Available",description:"Get ready to inspire the next generation of engineers at Perth Robogals workshops."},
  {id:2,date:"2026-07-08",day:8,title:"School Outreach Facilitator Training",start:"13:00",end:"14:00",location:"UWA EZONE · Flexi Room",capacity:12,booked:10,status:"Nearly Full",description:"Practical training for volunteers delivering engaging school outreach sessions."},
  {id:3,date:"2026-07-08",day:8,title:"Robotics Workshop Volunteer Induction",start:"15:00",end:"16:30",location:"UWA EZONE · Learning Studio",capacity:18,booked:18,status:"Full",description:"Get ready to inspire the next generation of engineers at Perth Robogals workshops."},
  {id:4,date:"2026-07-14",day:14,title:"Inclusive STEM Facilitation",start:"10:00",end:"11:30",location:"Perth City · Community Lab",capacity:24,booked:9,status:"Available",description:"Build confidence creating welcoming, inclusive and hands-on STEM experiences."},
  {id:5,date:"2026-07-21",day:21,title:"Robotics Kit & Equipment Training",start:"11:00",end:"12:30",location:"UWA EZONE · Maker Space",capacity:10,booked:6,status:"Available",description:"Hands-on practice with the robotics kits used in Perth Robogals workshops."},
  {id:6,date:"2026-07-26",day:26,title:"School Outreach Facilitator Training",start:"14:00",end:"15:00",location:"UWA EZONE · Flexi Room",capacity:12,booked:4,status:"Closed",description:"Registrations closed at the published deadline."},
];

const testNames = ["Mia Thompson","Ethan Nguyen","Aisha Rahman","Sophie Williams","Noah Chen","Grace Patel","Liam Martin","Zara Wilson","Oliver Kim","Amelia Brown","Lucas Singh","Chloe Taylor","Jack Lee","Isla Johnson","Henry Davis","Ruby Walker","Leo Thomas","Ava Robinson"];
const seedRegistrations: Registration[] = seed.flatMap(s=>Array.from({length:s.booked},(_,i)=>({id:s.id*100+i,sessionId:s.id,name:testNames[(s.id*3+i)%testNames.length],studentNumber:String(22000000+s.id*1000+i*37),status:"Confirmed" as const})));

const monthNames = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const dow = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function effective(s:Session):Status { if(s.status!=="Available") return s.status; if(s.booked>=s.capacity) return "Full"; if(s.booked/s.capacity>=.75) return "Nearly Full"; return "Available"; }
function fmtDate(year:number,month:number,day:number){return `${String(day).padStart(2,"0")}/${String(month+1).padStart(2,"0")}/${year}`}
function fmtIso(date:string){const [year,month,day]=date.split("-");return `${day}/${month}/${year}`}

export default function Home(){
  const now=new Date();
  const [view,setView]=useState({year:now.getFullYear(),month:now.getMonth()});
  const [sessions,setSessions]=useState<Session[]>([]);
  const [selected,setSelected]=useState<Session|null>(null);
  const [adminSession,setAdminSession]=useState<Session|null>(null);
  const [creating,setCreating]=useState(false);
  const [registrations,setRegistrations]=useState<Registration[]>([]);
  const [screen,setScreen]=useState<"calendar"|"info"|"admin">("calendar");
  const [admin,setAdmin]=useState(false);
  const [monthMenu,setMonthMenu]=useState(false);
  const [confirmation,setConfirmation]=useState<{ref:string;session:Session}|null>(null);
  const [notice,setNotice]=useState("");
  const [query,setQuery]=useState("");
  const [filter,setFilter]=useState("Upcoming");
  const [loading,setLoading]=useState(true);
  const days=useMemo(()=>{const first=(new Date(view.year,view.month,1).getDay()+6)%7;const count=new Date(view.year,view.month+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)]},[view]);
  const visibleSessions=sessions.filter(s=>s.date.startsWith(`${view.year}-${String(view.month+1).padStart(2,"0")}`));
  useEffect(()=>{void refreshSessions();void checkAdmin()},[]);
  async function refreshSessions(){try{const res=await fetch("/api/sessions",{cache:"no-store"});if(res.ok){const data=await res.json();setSessions(data.sessions.map((s:Session&{status:string})=>({...s,day:Number(s.date.slice(8,10)),booked:Number(s.booked),capacity:Number(s.capacity),status:s.status==="closed"?"Closed":"Available"})))}}finally{setLoading(false)}}
  async function checkAdmin(){const res=await fetch("/api/admin",{cache:"no-store"});if(res.ok){const data=await res.json();setAdmin(true);setRegistrations(data.registrations.map((r:Registration&{status:string})=>({...r,status:r.status==="confirmed"?"Confirmed":"Waitlisted"})))}}
  const changeMonth=(d:number)=>{const x=new Date(view.year,view.month+d,1);setView({year:x.getFullYear(),month:x.getMonth()})};
  const bookable=(s:Session)=>["Available","Nearly Full"].includes(effective(s));
  async function submitBooking(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setNotice("");const fd=new FormData(e.currentTarget);const s=selected!;const res=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:s.id,name:fd.get("name"),studentNumber:fd.get("student"),email:fd.get("email"),company:fd.get("company")})});const data=await res.json();if(!res.ok){setNotice(data.error||"Registration failed.");return}setConfirmation({ref:data.reference,session:s});setSelected(null);await refreshSessions()}
  async function createSession(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload={title:fd.get("title"),description:fd.get("description"),date:fd.get("date"),location:fd.get("location"),start:fd.get("start"),end:fd.get("end"),capacity:Number(fd.get("capacity"))};const res=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!res.ok){setNotice("Session could not be created.");return}const date=new Date(String(payload.date)+"T12:00:00");setView({year:date.getFullYear(),month:date.getMonth()});setCreating(false);await refreshSessions()}
  async function deleteSession(s:Session){if(confirm(`Delete “${s.title}”? This removes it from the calendar and cannot be undone.`)){const res=await fetch(`/api/admin?id=${encodeURIComponent(String(s.id))}`,{method:"DELETE"});if(res.ok){setAdminSession(null);await refreshSessions();await checkAdmin()}}}
  function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();window.location.href="/signin-with-chatgpt?return_to=%2F%3Fadmin%3D1"}
  function exportCsv(){const rows=["Session,Date,Time,Location,Booked,Capacity",...sessions.map(s=>`\"${s.title}\",${fmtDate(view.year,view.month,s.day)},${s.start}-${s.end},\"${s.location}\",${s.booked},${s.capacity}`)];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));a.download="training-sessions-test-data.csv";a.click()}
  return <main>
    <header className="top"><a className="brand" href="#" onClick={()=>setScreen("calendar")}><img src="/robogals-perth-logo.png" alt="Robogals Perth Asia Pacific"/><span><b>Volunteer Training</b><small>Perth chapter</small></span></a><nav aria-label="Primary navigation"><button className={screen==="calendar"?"active":""} onClick={()=>setScreen("calendar")}>Calendar</button><button className={screen==="info"?"active":""} onClick={()=>setScreen("info")}>Booking information</button><button className={screen==="admin"?"active":""} onClick={()=>setScreen("admin")}>{admin?"Admin dashboard":"Admin login"}</button></nav></header>
    {screen==="calendar"&&<>
      <section className="hero"><img className="hero-bot" src="/robogals-wordmark.png" alt=""/><div><span className="eyebrow">PERTH ROBOGALS</span><h1>Learn. Build. Inspire.</h1><p>Book your volunteer training and get ready to bring fun, hands-on engineering workshops to young people across Perth.</p></div><div className="timezone"><span>◷</span><div><small>Times shown in</small><b>Australia / Perth (AWST)</b></div></div></section>
      <section className="calendar-card">
        <div className="cal-head"><div><h2>{monthNames[view.month]} {view.year}</h2><p>Select a highlighted day to see sessions.</p></div><div className="cal-actions"><button aria-label="Previous month" onClick={()=>changeMonth(-1)}>←</button><button onClick={()=>setView({year:now.getFullYear(),month:now.getMonth()})}>Today</button><button aria-label="Next month" onClick={()=>changeMonth(1)}>→</button></div></div>
        <div className="calendar"><div className="week">{dow.map(d=><b key={d}>{d}</b>)}</div><div className="grid">{days.map((day,i)=>day===null?<div className="cell muted" key={`x${i}`}/>:<div className={`cell ${visibleSessions.some(s=>s.day===day)?"has":""}`} key={day}><span className="day">{day}</span><div className="events">{visibleSessions.filter(s=>s.day===day).map(s=><button key={s.id} className={`event ${effective(s).toLowerCase().replace(" ","-")}`} disabled={!bookable(s)} onClick={()=>setSelected(s)} aria-label={`${s.title}, ${s.start}, ${effective(s)}`}><span>{s.start}</span><b>{s.title}</b><small>{s.location.split(" · ")[0]}</small></button>)}</div></div>)}</div></div>
        <div className="legend"><b>Status</b>{["Available","Nearly Full","Full","Closed"].map(x=><span key={x} className={`key ${x.toLowerCase().replace(" ","-")}`}>{x}</span>)}</div>
      </section>
      <section className="help"><div className="help-icon">?</div><div><h3>Need help with your booking?</h3><p>For changes or cancellations, contact the Perth Robogals team at <a href="mailto:perth@robogals.org">perth@robogals.org</a>. Have your booking reference ready.</p></div></section>
    </>}
    {screen==="info"&&<section className="simple"><span className="eyebrow">VOLUNTEER BOOKING</span><h1>Before you book</h1><div className="info-grid"><article><b>1</b><h3>Choose a session</h3><p>Pick an Available or Nearly Full training session that suits you.</p></article><article><b>2</b><h3>Enter your details</h3><p>You’ll need your full name and 6–10 digit student number.</p></article><article><b>3</b><h3>Get workshop-ready</h3><p>Save your booking reference and bring your enthusiasm for STEM.</p></article></div><h2>Changing or cancelling</h2><p>Email <a href="mailto:perth@robogals.org">perth@robogals.org</a> with your name, student number and booking reference. Please do not submit a second booking for the same session.</p></section>}
    {screen==="admin"&&!admin&&<section className="login"><div><span className="eyebrow">ROBOGALS TEAM ACCESS</span><h1>Administrator login</h1><p>Authorised Perth chapter coordinators only. Volunteer bookings do not require an account.</p><form onSubmit={login}><button className="primary">Sign in securely with ChatGPT</button><small>Administrator access is authenticated and checked on the server.</small></form></div></section>}
    {screen==="admin"&&admin&&<section className="dashboard"><div className="dash-title"><div><span className="eyebrow">ADMINISTRATION</span><h1>Training sessions</h1><p>Manage availability and registrations. All records below are test data.</p></div><button className="primary" onClick={()=>setCreating(true)}>＋ Create session</button></div><div className="stats"><article><small>Upcoming sessions</small><b>{sessions.length}</b><span>Across {new Set(sessions.map(s=>s.day)).size} dates</span></article><article><small>Total registrations</small><b>{sessions.reduce((a,s)=>a+s.booked,0)}</b><span>of {sessions.reduce((a,s)=>a+s.capacity,0)} places</span></article><article><small>Nearly full / full</small><b>{sessions.filter(s=>["Nearly Full","Full"].includes(effective(s))).length}</b><span>Needs attention</span></article></div><div className="admin-tools"><div className="tabs">{["Upcoming","Available","Full","Closed","Past","Cancelled"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="search"><input aria-label="Search registrations" placeholder="Search name or student number" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={exportCsv}>Export CSV</button><button onClick={()=>window.print()}>Print</button></div></div><div className="session-list">{sessions.filter(s=>filter==="Upcoming"||effective(s)===filter).map(s=><article key={s.id}><div className="datebox"><b>{s.day}</b><span>{monthNames[view.month].slice(0,3)}</span></div><div className="session-main"><div><span className={`badge ${effective(s).toLowerCase().replace(" ","-")}`}>{effective(s)}</span><h3>{s.title}</h3><p>{s.start}–{s.end} · {s.location}</p></div><div className="capacity"><b>{s.booked}/{s.capacity}</b><span>registered</span></div><div className="row-actions"><button onClick={()=>setAdminSession(s)}>View attendees</button><button onClick={()=>{const copy={...s,id:Date.now(),title:`${s.title} (copy)`,booked:0};setSessions(a=>[...a,copy])}}>Duplicate</button><button aria-label={`Delete ${s.title}`} title="Delete session" onClick={()=>deleteSession(s)}>•••</button></div></div></article>)}</div></section>}
    {creating&&<div className="modal-back" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setCreating(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="create-title"><button className="close" onClick={()=>setCreating(false)} aria-label="Close">×</button><span className="eyebrow">NEW TRAINING SESSION</span><h2 id="create-title">Create a session</h2><p>Once saved, the session will appear immediately on the public calendar.</p><form onSubmit={createSession}><label>Session title<input name="title" required placeholder="e.g. Robotics Workshop Induction"/></label><label>Description<input name="description" required placeholder="What volunteers will learn"/></label><div className="two"><label>Date<input name="date" type="date" required min={`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`}/></label><label>Location<input name="location" required placeholder="Venue and room"/></label></div><div className="three"><label>Start time<input name="start" type="time" required/></label><label>End time<input name="end" type="time" required/></label><label>Capacity<input name="capacity" type="number" min="1" max="200" defaultValue="20" required/></label></div><div className="modal-actions"><button type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary">Create session</button></div></form></section></div>}
    {adminSession&&<div className="modal-back" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setAdminSession(null)}}><section className="modal attendee-modal" role="dialog" aria-modal="true" aria-labelledby="attendee-title"><button className="close" onClick={()=>setAdminSession(null)} aria-label="Close">×</button><span className="eyebrow">SESSION REGISTRATIONS</span><h2 id="attendee-title">{adminSession.title}</h2><p>{fmtDate(view.year,view.month,adminSession.day)} · {adminSession.start}–{adminSession.end} · {adminSession.location}</p><div className="attendee-head"><div><b>{adminSession.booked}</b><span>registered</span></div><input aria-label="Search attendee list" placeholder="Search name or student number" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="attendee-list"><div className="attendee-row attendee-labels"><span>Name</span><span>Student number</span><span>Status</span></div>{registrations.filter(r=>r.sessionId===adminSession.id&&(r.name.toLowerCase().includes(query.toLowerCase())||r.studentNumber.includes(query))).map(r=><div className="attendee-row" key={r.id}><b>{r.name}</b><span>{r.studentNumber}</span><span className="badge">{r.status}</span></div>)}{registrations.filter(r=>r.sessionId===adminSession.id).length===0&&<p className="empty-state">No registrations for this session yet.</p>}</div><div className="modal-actions"><button className="danger" onClick={()=>deleteSession(adminSession)}>Delete session</button><button className="primary" onClick={()=>setAdminSession(null)}>Done</button></div></section></div>}
    {selected&&<div className="modal-back" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="close" onClick={()=>setSelected(null)} aria-label="Close">×</button><span className={`badge ${effective(selected).toLowerCase().replace(" ","-")}`}>{effective(selected)}</span><h2 id="booking-title">{selected.title}</h2><p>{selected.description}</p><div className="summary"><div><small>Date</small><b>{fmtDate(view.year,view.month,selected.day)}</b></div><div><small>Time</small><b>{selected.start}–{selected.end}</b></div><div><small>Location</small><b>{selected.location}</b></div><div><small>Spaces remaining</small><b>{selected.capacity-selected.booked} of {selected.capacity}</b></div></div>{bookable(selected)&&screen!=="admin"?<form onSubmit={submitBooking}><div className="two"><label>Full name<input name="name" required minLength={2} autoComplete="name"/></label><label>Student number<input name="student" required inputMode="numeric" pattern="[0-9]{6,10}"/></label></div><label>Email address <em>(optional)</em><input name="email" type="email" autoComplete="email"/></label>{notice&&<p className="error" role="alert">{notice}</p>}<label className="check"><input type="checkbox" required/><span>I confirm my details and the selected date and time are correct.</span></label><button className="primary">Confirm booking</button></form>:<button className="primary" onClick={()=>setSelected(null)}>Close</button>}</section></div>}
    {confirmation&&<div className="modal-back"><section className="modal confirmation" role="dialog" aria-modal="true"><div className="tick">✓</div><span className="eyebrow">BOOKING CONFIRMED</span><h2>Your place is reserved</h2><p>Keep this reference for any changes or cancellations.</p><div className="reference"><small>Booking reference</small><b>{confirmation.ref}</b></div><div className="summary"><div><small>Training</small><b>{confirmation.session.title}</b></div><div><small>Date & time</small><b>{fmtDate(view.year,view.month,confirmation.session.day)} · {confirmation.session.start}–{confirmation.session.end}</b></div><div><small>Location</small><b>{confirmation.session.location}</b></div></div><button className="primary" onClick={()=>setConfirmation(null)}>Return to calendar</button></section></div>}
    <footer><span>© {now.getFullYear()} Robogals Perth Asia Pacific</span><span>Inspiring tomorrow’s engineers · Accessibility · Contact</span></footer>
  </main>
}
