"use client";

import { useMemo, useState } from "react";

type Status = "Available" | "Nearly Full" | "Full" | "Closed" | "Cancelled" | "Completed";
type Session = { id:number; day:number; title:string; start:string; end:string; location:string; capacity:number; booked:number; status:Status; description:string };

const seed: Session[] = [
  {id:1,day:3,title:"Laboratory Safety Induction",start:"09:00",end:"10:30",location:"Science Building · Lab 2.14",capacity:18,booked:7,status:"Available",description:"Essential induction for students working in teaching laboratories."},
  {id:2,day:8,title:"Fieldwork Safety Briefing",start:"13:00",end:"14:00",location:"Learning Hub · Room 1.06",capacity:12,booked:10,status:"Nearly Full",description:"Preparation and safety guidance for off-campus fieldwork."},
  {id:3,day:8,title:"Laboratory Safety Induction",start:"15:00",end:"16:30",location:"Science Building · Lab 2.14",capacity:18,booked:18,status:"Full",description:"Essential induction for students working in teaching laboratories."},
  {id:4,day:14,title:"Research Data Essentials",start:"10:00",end:"11:30",location:"Library · Seminar Room 3",capacity:24,booked:9,status:"Available",description:"Practical foundations for safely managing research data."},
  {id:5,day:21,title:"Workshop Equipment Induction",start:"11:00",end:"12:30",location:"Engineering · Workshop 1",capacity:10,booked:6,status:"Available",description:"Hands-on equipment and workshop safety induction."},
  {id:6,day:26,title:"Fieldwork Safety Briefing",start:"14:00",end:"15:00",location:"Learning Hub · Room 1.06",capacity:12,booked:4,status:"Closed",description:"Registrations closed at the published deadline."},
];

const monthNames = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const dow = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function effective(s:Session):Status { if(s.status!=="Available") return s.status; if(s.booked>=s.capacity) return "Full"; if(s.booked/s.capacity>=.75) return "Nearly Full"; return "Available"; }
function fmtDate(year:number,month:number,day:number){return `${String(day).padStart(2,"0")}/${String(month+1).padStart(2,"0")}/${year}`}

export default function Home(){
  const now=new Date();
  const [view,setView]=useState({year:now.getFullYear(),month:now.getMonth()});
  const [sessions,setSessions]=useState(seed);
  const [selected,setSelected]=useState<Session|null>(null);
  const [screen,setScreen]=useState<"calendar"|"info"|"admin">("calendar");
  const [admin,setAdmin]=useState(false);
  const [monthMenu,setMonthMenu]=useState(false);
  const [confirmation,setConfirmation]=useState<{ref:string;session:Session}|null>(null);
  const [notice,setNotice]=useState("");
  const [query,setQuery]=useState("");
  const [filter,setFilter]=useState("Upcoming");
  const days=useMemo(()=>{const first=(new Date(view.year,view.month,1).getDay()+6)%7;const count=new Date(view.year,view.month+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)]},[view]);
  const changeMonth=(d:number)=>{const x=new Date(view.year,view.month+d,1);setView({year:x.getFullYear(),month:x.getMonth()})};
  const bookable=(s:Session)=>["Available","Nearly Full"].includes(effective(s));
  function submitBooking(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const student=String(fd.get("student")||"").trim();if(!/^\d{6,10}$/.test(student)){setNotice("Enter a valid student number (6–10 digits).");return}const s=selected!;setSessions(a=>a.map(x=>x.id===s.id?{...x,booked:x.booked+1}:x));setConfirmation({ref:`TRN-${view.year}-${String(Math.floor(Math.random()*90000)+10000)}`,session:s});setSelected(null);setNotice("")}
  function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setAdmin(true)}
  function exportCsv(){const rows=["Session,Date,Time,Location,Booked,Capacity",...sessions.map(s=>`\"${s.title}\",${fmtDate(view.year,view.month,s.day)},${s.start}-${s.end},\"${s.location}\",${s.booked},${s.capacity}`)];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));a.download="training-sessions-test-data.csv";a.click()}
  return <main>
    <header className="top"><a className="brand" href="#" onClick={()=>setScreen("calendar")}><span className="mark">W</span><span><b>Westland University</b><small>Training & Inductions</small></span></a><nav aria-label="Primary navigation"><button className={screen==="calendar"?"active":""} onClick={()=>setScreen("calendar")}>Calendar</button><button className={screen==="info"?"active":""} onClick={()=>setScreen("info")}>Booking information</button><button className={screen==="admin"?"active":""} onClick={()=>setScreen("admin")}>{admin?"Admin dashboard":"Admin login"}</button></nav></header>
    {screen==="calendar"&&<>
      <section className="hero"><div><span className="eyebrow">STUDENT TRAINING</span><h1>Book your training session</h1><p>Choose a highlighted date, select a time, and confirm your place. No account or sign-in required.</p></div><div className="timezone"><span>◷</span><div><small>Times shown in</small><b>Australia / Perth (AWST)</b></div></div></section>
      <div className="test-banner"><b>Test environment</b><span>Sessions and registrations shown here are sample data for evaluation.</span></div>
      <section className="calendar-card">
        <div className="cal-head"><div><h2>{monthNames[view.month]} {view.year}</h2><p>Select a highlighted day to see sessions.</p></div><div className="cal-actions"><button aria-label="Previous month" onClick={()=>changeMonth(-1)}>←</button><button onClick={()=>setView({year:now.getFullYear(),month:now.getMonth()})}>Today</button><button aria-label="Next month" onClick={()=>changeMonth(1)}>→</button></div></div>
        <div className="calendar"><div className="week">{dow.map(d=><b key={d}>{d}</b>)}</div><div className="grid">{days.map((day,i)=>day===null?<div className="cell muted" key={`x${i}`}/>:<div className={`cell ${sessions.some(s=>s.day===day)?"has":""}`} key={day}><span className="day">{day}</span><div className="events">{sessions.filter(s=>s.day===day).map(s=><button key={s.id} className={`event ${effective(s).toLowerCase().replace(" ","-")}`} disabled={!bookable(s)} onClick={()=>setSelected(s)} aria-label={`${s.title}, ${s.start}, ${effective(s)}`}><span>{s.start}</span><b>{s.title}</b><small>{s.location.split(" · ")[0]}</small></button>)}</div></div>)}</div></div>
        <div className="legend"><b>Status</b>{["Available","Nearly Full","Full","Closed"].map(x=><span key={x} className={`key ${x.toLowerCase().replace(" ","-")}`}>{x}</span>)}</div>
      </section>
      <section className="help"><div className="help-icon">?</div><div><h3>Need help with your booking?</h3><p>For changes or cancellations, contact the Training Support team at <a href="mailto:training@westland.edu.au">training@westland.edu.au</a> or (08) 6123 4567. Have your booking reference ready.</p></div></section>
    </>}
    {screen==="info"&&<section className="simple"><span className="eyebrow">BOOKING INFORMATION</span><h1>Before you book</h1><div className="info-grid"><article><b>1</b><h3>Choose a session</h3><p>Only sessions marked Available or Nearly Full can be booked.</p></article><article><b>2</b><h3>Enter your details</h3><p>You’ll need your full name and 6–10 digit student number.</p></article><article><b>3</b><h3>Keep your reference</h3><p>Save the unique reference shown after your booking is confirmed.</p></article></div><h2>Changing or cancelling</h2><p>Email <a href="mailto:training@westland.edu.au">training@westland.edu.au</a> with your name, student number and booking reference. Please do not submit a second booking for the same session.</p></section>}
    {screen==="admin"&&!admin&&<section className="login"><div><span className="eyebrow">RESTRICTED ACCESS</span><h1>Administrator login</h1><p>Authorised training staff only. Student bookings do not require an account.</p><form onSubmit={login}><label>Email address<input type="email" required defaultValue="admin@westland.edu.au"/></label><label>Password<input type="password" required defaultValue="training-demo"/></label><button className="primary">Sign in securely</button><small>Demo credentials are pre-filled for this test environment.</small></form></div></section>}
    {screen==="admin"&&admin&&<section className="dashboard"><div className="dash-title"><div><span className="eyebrow">ADMINISTRATION</span><h1>Training sessions</h1><p>Manage availability and registrations. All records below are test data.</p></div><button className="primary" onClick={()=>alert("New session form would open here.")}>＋ Create session</button></div><div className="stats"><article><small>Upcoming sessions</small><b>6</b><span>Across 5 dates</span></article><article><small>Total registrations</small><b>{sessions.reduce((a,s)=>a+s.booked,0)}</b><span>of {sessions.reduce((a,s)=>a+s.capacity,0)} places</span></article><article><small>Nearly full / full</small><b>{sessions.filter(s=>["Nearly Full","Full"].includes(effective(s))).length}</b><span>Needs attention</span></article></div><div className="admin-tools"><div className="tabs">{["Upcoming","Available","Full","Closed","Past","Cancelled"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="search"><input aria-label="Search registrations" placeholder="Search name or student number" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={exportCsv}>Export CSV</button><button onClick={()=>window.print()}>Print</button></div></div><div className="session-list">{sessions.filter(s=>filter==="Upcoming"||effective(s)===filter).map(s=><article key={s.id}><div className="datebox"><b>{s.day}</b><span>{monthNames[view.month].slice(0,3)}</span></div><div className="session-main"><div><span className={`badge ${effective(s).toLowerCase().replace(" ","-")}`}>{effective(s)}</span><h3>{s.title}</h3><p>{s.start}–{s.end} · {s.location}</p></div><div className="capacity"><b>{s.booked}/{s.capacity}</b><span>registered</span></div><div className="row-actions"><button onClick={()=>setSelected(s)}>View</button><button onClick={()=>alert("A duplicate session draft has been created.")}>Duplicate</button><button onClick={()=>confirm("Cancel this session? Registered students will need to be notified.")&&setSessions(a=>a.map(x=>x.id===s.id?{...x,status:"Cancelled"}:x))}>•••</button></div></div></article>)}</div></section>}
    {selected&&<div className="modal-back" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="close" onClick={()=>setSelected(null)} aria-label="Close">×</button><span className={`badge ${effective(selected).toLowerCase().replace(" ","-")}`}>{effective(selected)}</span><h2 id="booking-title">{selected.title}</h2><p>{selected.description}</p><div className="summary"><div><small>Date</small><b>{fmtDate(view.year,view.month,selected.day)}</b></div><div><small>Time</small><b>{selected.start}–{selected.end}</b></div><div><small>Location</small><b>{selected.location}</b></div><div><small>Spaces remaining</small><b>{selected.capacity-selected.booked} of {selected.capacity}</b></div></div>{bookable(selected)&&screen!=="admin"?<form onSubmit={submitBooking}><div className="two"><label>Full name<input name="name" required minLength={2} autoComplete="name"/></label><label>Student number<input name="student" required inputMode="numeric" pattern="[0-9]{6,10}"/></label></div><label>Email address <em>(optional)</em><input name="email" type="email" autoComplete="email"/></label>{notice&&<p className="error" role="alert">{notice}</p>}<label className="check"><input type="checkbox" required/><span>I confirm my details and the selected date and time are correct.</span></label><button className="primary">Confirm booking</button></form>:<button className="primary" onClick={()=>setSelected(null)}>Close</button>}</section></div>}
    {confirmation&&<div className="modal-back"><section className="modal confirmation" role="dialog" aria-modal="true"><div className="tick">✓</div><span className="eyebrow">BOOKING CONFIRMED</span><h2>Your place is reserved</h2><p>Keep this reference for any changes or cancellations.</p><div className="reference"><small>Booking reference</small><b>{confirmation.ref}</b></div><div className="summary"><div><small>Training</small><b>{confirmation.session.title}</b></div><div><small>Date & time</small><b>{fmtDate(view.year,view.month,confirmation.session.day)} · {confirmation.session.start}–{confirmation.session.end}</b></div><div><small>Location</small><b>{confirmation.session.location}</b></div></div><button className="primary" onClick={()=>setConfirmation(null)}>Return to calendar</button></section></div>}
    <footer><span>© {now.getFullYear()} Westland University · Training Services</span><span>Privacy · Accessibility · Contact</span></footer>
  </main>
}
